name: publish docs

on:
  push:
    branches-ignore:
      - v*
    tags-ignore:
      - v*

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.400

      - run: dotnet restore
      - run: dotnet tool restore
      - run: dotnet docfx -m pdf=false docs/docfx.json

      - name: update default docs
        run: |
          set -ev

          if [[ "${{ github.ref_name }}" =~ ^v ]]; then
            echo "Prevent tags started with 'v'" >&2
            exit
          fi

          latest_version=$(git tag --sort -v:refname | grep -E -i '^\d+\.\d+\.\d+' | head -n 1)
          if [[ "$latest_version" = "${{ github.ref_name }}" ]]; then
            index=$(cat docs/_site/index.html)
            {
              echo -n "${index%</title>*}</title>"
              echo "<meta http-equiv=\"refresh\" content=\"0;$slug/\">"
              echo "<base href=\"$slug/\">"
              echo -n "${index#*</title>}"
            } > /tmp/gh-pages-root/index.html
          fi
        if: ${{ github.ref_type }} == 'tag'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site/
          destination_dir: ${{ github.ref_name }}
      - name: deploy (index.html)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tmp/gh-pages-root
          destination_dir: .
          keep_files: true
        if: ${{ github.ref_type }} == 'tag'
